package sk.zaymus.sub.ui;

import java.util.List;
import sk.zaymus.sub.opensubtitles.OSConfig;
import sk.zaymus.sub.pojo.Language;

/**
 * Panel representing settings window.
 *
 * @author Mikulas Zaymus
 */
public class SettingsPanel extends javax.swing.JPanel {

    private final OSConfig config = OSConfig.getConfig();
    private final JCheckBoxListModel model = new JCheckBoxListModel();
    private final JCheckBoxListCellRender render = new JCheckBoxListCellRender();

    /**
     *
     * @param selectedTabIdx index of tab, that should be in foreground
     * @param langs supported languages
     */
    public SettingsPanel(int selectedTabIdx, List<Language> langs) {
        initComponents();
        tabbedPane.setSelectedIndex(selectedTabIdx);
        model.addAll(langs);
        if (config.getSubLanguageIDs().equals(OSConfig.ALL_LANGUAGES)) {
            cbAllLang.setSelected(true);
            model.setSelectedAll(true);
        } else {
            model.setSelected(config.getSubLanguageIDs().split(OSConfig.LANGUAGES_SEPARATOR));
        }
        list.repaint();
    }

    /**
     * Saves setting in {@link OSConfig}.
     */
    public void saveChanges() {
        String user = txtUserName.getText();
        String pass = txtPassword.getText();
        if (user.length() == 0 && pass.length() == 0 || user.length() > 0 && pass.length() > 0) {
            config.setUserName(user);
            config.setPassword(pass);
        }
        config.setSubLanguageIDs(cbAllLang.isSelected() ? OSConfig.ALL_LANGUAGES : model.getSubLanguageID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        logInPanel = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField(config.getUserName());
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField(config.getPassword());
        languagePanel = new javax.swing.JPanel();
        lblListHeading = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        cbAllLang = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        lblUserName.setText("User Name:");

        lblPassword.setText("Password:");

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName)
                    .addComponent(lblPassword))
                .addGap(12, 12, 12)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logInPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUserName});

        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Log In", logInPanel);

        lblListHeading.setText("Subtitle Language:");

        list.setCellRenderer(render);
        list.setModel(model);
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(list);

        cbAllLang.setText("All Languages");
        cbAllLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAllLangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout languagePanelLayout = new javax.swing.GroupLayout(languagePanel);
        languagePanel.setLayout(languagePanelLayout);
        languagePanelLayout.setHorizontalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(languagePanelLayout.createSequentialGroup()
                        .addComponent(lblListHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAllLang))
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        languagePanelLayout.setVerticalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListHeading)
                    .addComponent(cbAllLang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane.addTab("Language", languagePanel);

        add(tabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        model.performClick(list.getSelectedIndex());
        list.repaint();
        cbAllLang.setSelected(model.isSelectedAll());
    }//GEN-LAST:event_listMouseClicked

    private void cbAllLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAllLangActionPerformed
        model.setSelectedAll(cbAllLang.isSelected());
        list.repaint();
    }//GEN-LAST:event_cbAllLangActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAllLang;
    private javax.swing.JPanel languagePanel;
    private javax.swing.JLabel lblListHeading;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JList list;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
